### ISSUE TITLE
Transparent right click menu

### ISSUE THREAD

**Issue by mariokhz** [nuclearcodecat/shimmer#1]
Hi! I'm on Arch Linux with Hyprland, and the theme has transparent effects on the top bar (when not using Sideberry) and in the right click menu.
![image](https://github.com/user-attachments/assets/8b428c5b-2569-43e9-a641-b47adf942eb3)

![Screenshot_08-nov_15-10-57_firefox](https://github.com/user-attachments/assets/dcb7e71a-520e-4f11-ab26-4ed217a226ad)

I've used some transparent chrome before, but I find it weird as they don't seem transparent in the screenshots of the theme.

I actually don't really care, in fact, I like how the top bar looks, but I found it strange and also wanted to say that I love the theme, so I posted this issue. Thank you.

**Comment by nuclearcodecat** [comment]
thanks for the nice words <3. what theme are you using?

**Comment by BeeverFeever** [comment]
This could be related to my issue #8 that was compositor related. I don't know much about wayland though so I can't really help much. However, my guess is that it is your wayland compositor(this is different to an X11 compositor, it's equivalent to an X11 window manager if that makes sense) making everything blury as it seems to be a consistent blur across the whole window. I could ofc be wrong though.

**Comment by mariokhz** [comment]
Hyprland blurs the background of every window, but the window has to be transparent to see it. In my KDE Plasma setup, it had a black strange color. Changing the theme from dark to dark again fixed the issue completely, and it is surely a misconfiguration I did. Thank you a lot.
