### ISSUE TITLE
Space under URL bar in new tab

### ISSUE THREAD

**Issue by djenttleman** [nuclearcodecat/shimmer#10]
Hi, here I am with new finds
In normal tabs with any page loaded looks normal

<img width="348" alt="imagen" src="https://github.com/user-attachments/assets/f47e4677-137e-45d9-9e22-74f6326b9cad">

But ONLY in new tab page there is a gap under url bar
<img width="341" alt="imagen" src="https://github.com/user-attachments/assets/25ac423c-54e0-499f-8c88-9046400c42dc">

Any ideas?

**Comment by nuclearcodecat** [comment]
i haven't seen this yet. looks like grid space isn't getting occupied by the personal toolbar or the personal toolbar is having some trouble with displaying🤔. i'm not sure why this would happen on newtab only though. are you sure you don't have any extensions that could mess with this?

**Comment by OutshineIssue** [comment]
It might be your bookmarks toolbar. Try Shift+⌘+B.

**Comment by djenttleman** [comment]
> It might be your bookmarks toolbar. Try Shift+⌘+B.

This is, thank you very much.
