### ISSUE TITLE
Unexpected dev tools element

### ISSUE THREAD

**Issue by ParussMan** [nuclearcodecat/shimmer#12]
![image](https://github.com/user-attachments/assets/cfb7af3b-2ed2-417f-91a7-1f227c3709fb)
Not sure how to describe it, but there's this weird thick line in dev tools

**Comment by nuclearcodecat** [comment]
which file affects it, `userChrome.css` or `userContent.css`? try removing one or the other and restarting

**Comment by nuclearcodecat** [comment]
fixed in v2.7

**Comment by nuclearcodecat** [comment]
sorry, i was trying some other stuff and forgot to swap the correct styles back in. now it works and i've checked. i'll just quietly update 2.7 without changing the number, so download 2.7 again and it should work
