### ISSUE TITLE
Transparent item lists in history

### ISSUE THREAD

**Issue by ParussMan** [nuclearcodecat/shimmer#13]
![image](https://github.com/user-attachments/assets/25b8de22-d6bd-4167-837f-a04189b220ca)
![image](https://github.com/user-attachments/assets/c0291bcc-fb1b-485b-a0ec-4ba5c2294442)

**Comment by nuclearcodecat** [comment]
issue reproduced, i'll try to fix this today if i have time

**Comment by nuclearcodecat** [comment]
fixed in v2.7
