### ISSUE TITLE
popover url-bar not centered

### ISSUE THREAD

**Issue by c3t1nn** [nuclearcodecat/shimmer#15]
![resim](https://github.com/user-attachments/assets/005f7d02-5d48-4271-83d7-259b940436d4)

Is it possible to center popover url-bar? 
I have a wide monitor, so maybe thats why. But when I need to use url bar, its in very left and making my neck hurt tbh.
Great art piece btw! Thx for your work.

**Comment by c3t1nn** [comment]
nwm, i already did somethings and send you pr

https://github.com/nuclearcodecat/shimmer/pull/16

**Comment by nuclearcodecat** [comment]
v2.10
