### ISSUE TITLE
Minimal Exit Menu

### ISSUE THREAD

**Issue by Mojas84** [nuclearcodecat/shimmer#17]
Hi we can do it for shimmer someone minimal exit menu as is on Zen Browser with this CSS??? = https://zen-browser.app/mods/6cd4bca9-f17d-4461-b554-844d69a4887c 
![obrazek](https://github.com/user-attachments/assets/aface849-ad7c-4e1b-88e0-25451dea367c)

**Comment by nuclearcodecat** [comment]
yeah i could do that. i will work on this, maybe today

**Comment by Mojas84** [comment]
> yeah i could do that. i will work on this, maybe today
OK Super!!

**Comment by nuclearcodecat** [comment]
![firefox_0QZQFIjRch](https://github.com/user-attachments/assets/3fb42621-227f-4b77-a238-3c6e7a802270)

releasing soon

**Comment by nuclearcodecat** [comment]
v2.10
