### ISSUE TITLE
no animation on active tab change and all tabs have the same width

### ISSUE THREAD

**Issue by moonfight1** [nuclearcodecat/shimmer#19]
[Screencast from 2024-11-17 18-21-23.webm](https://github.com/user-attachments/assets/55c2bf64-090e-48f2-a5c9-0313cfb15409)

i feel like im missing something but in the gif in the README it shows the active tab being wider and having an animation for that but that doesnt work for me

**Comment by nuclearcodecat** [comment]
it's for visibility when you have a lot of tabs open, try with 20

**Comment by moonfight1** [comment]
oh lol, i thought that was intended

**Comment by moonfight1** [comment]
is there a way to set the width of tabs then

**Comment by nuclearcodecat** [comment]
i tried to make them smaller with `.tabbrowser-tab:not([pinned]) {max-width: 14em !important;}` but it breaks like everything, you can try yourself and see what i mean

**Comment by moonfight1** [comment]
okay in that case can you add an option that reverts to the old shimmer tabs, the ones that had no active tab width change but were thinner

**Comment by nuclearcodecat** [comment]
just an option to remove the width change?

**Comment by moonfight1** [comment]
yeah

**Comment by nuclearcodecat** [comment]
sure i'll include it in v2.13 :P
