### ISSUE TITLE
Can I use it without the installation of extension?

### ISSUE THREAD

**Issue by saltsoftdrink** [nuclearcodecat/shimmer#2]
The title

**Comment by nuclearcodecat** [comment]
yes, there are styles for native tabs too. there is no need for sidebery

**Comment by saltsoftdrink** [comment]
> yes, there are styles for native tabs too. there is no need for sidebery

Sorry I'm new to this can you give a guide

**Comment by saltsoftdrink** [comment]
Sorry, I'm new to this can you give me a guide

**Comment by nuclearcodecat** [comment]
you don't need to do anything. just follow the installation instructions but ignore the sidebery steps
