### ISSUE TITLE
What is the reason for not displaying these two?

### ISSUE THREAD

**Issue by OutshineIssue** [nuclearcodecat/shimmer#23]
```
#toolbar-menubar {
  display: none !important;
}
```
I use the menu bar frequently, so this line is quite frustrating.

```
.titlebar-spacer {
  display: none !important;
}
```
This is causing some layout issues for me, and I can't find any reason for it not to be displayed.

**Comment by OutshineIssue** [comment]
Could you please add the current version as a comment at the top of the userChrome file for easier tracking? Additionally, if possible, please include support for [this Add-on](https://addons.mozilla.org/en-US/firefox/addon/userchrome-toggle/). Thank you!

**Comment by nuclearcodecat** [comment]
sure, i'll add the version comment. i don't remember why exactly did i delete them, i'll check it out at home. as for the extension, what would it be used for?

**Comment by nuclearcodecat** [comment]
hi, i checked them out. how about i just keep the spacers when native tabs are used and remove them in the compact layout? the spacer on the right frustrates me a bit so that's why they were removed. i think it also wouldn't hurt if they were 50% their regular width, let me know. i think the menubar messed with some things in early development so i just removed it and forgot. i'll try modifying the grid code so it works properly

![image](https://github.com/user-attachments/assets/99d087a3-6210-4dba-a671-b97bccf10779)
spacer i mentioned

**Comment by OutshineIssue** [comment]
Oh gotcha, yeah I see the problem. I'm using the new Mica flag introduced in the latest Nightly build, and it overrides Firefox's default minimize, maximize, and close buttons, which are being modified by shimmer, with those native of Windows.

So after unchecking this `opacity:0` that they added for users with Mica enabled...
![image](https://github.com/user-attachments/assets/b0ce0adf-3c3d-44e8-a5e8-c4a3f8622903)

I'm left with this mess...
![image](https://github.com/user-attachments/assets/6673eb77-f5a0-4447-ab2f-f6c467faef4f)

Which is why `.titlebar-spacer {display: none !important;}` ruins my layout.

I guess I can fix this in my own fork, so I don't bloat the og code for a specific use case like mine; I could use the same `@media (-moz-windows-mica) { yada yada }` that Firefox's engineers used.

**Comment by nuclearcodecat** [comment]
i already fixed up the menubar on nightly (it's a bit more difficult on native) so hold on for now :P

**Comment by nuclearcodecat** [comment]
i guess i should close this? the spacers are fixed and the menubar is kind of fixed

**Comment by OutshineIssue** [comment]
Yeah go ahead, not 100% fixed on my end but I use some weird ass flags so do not worry.
