### ISSUE TITLE
Rounded corners disappear on some websites

### ISSUE THREAD

**Issue by jtayobong** [nuclearcodecat/shimmer#24]
![image](https://github.com/user-attachments/assets/ff449e86-31b1-4f89-9b79-c016ad9f938b)

**Comment by nuclearcodecat** [comment]
i've seen this. not sure why it's happening. overflows are hidden. someone was dm'ing me about fixing some issues with the borders using `clip-path`. i'll look into it

**Comment by nuclearcodecat** [comment]
fixed in v2.16 :3
