### ISSUE TITLE
Fullscreen videoplayer still shows browser border

### ISSUE THREAD

**Issue by d-aritos** [nuclearcodecat/shimmer#27]
Border showing through in blue
![Screenshot 2024-11-25 200822](https://github.com/user-attachments/assets/8b725bd5-fc28-43c8-b9ad-724ad44bc0ac)

**Comment by nuclearcodecat** [comment]
unfixable atm i think, you have to press f1 and "hide" sidebery. it might look like it's hidden, but the attribute isn't there and the styles still apply

**Comment by OutshineIssue** [comment]
@nuclearcodecat Perhaps a boolean setting in about:config to disable those rounded borders?

**Comment by nuclearcodecat** [comment]
sure i don't mind. tomorrow i should be able to add it

**Comment by nuclearcodecat** [comment]
fixed in v2.19 :P, releasing soon

**Comment by d-aritos** [comment]
thank you so much! loving this project :)
