### ISSUE TITLE
Findbar background and icons missing on Mac - unreadable in many situations

### ISSUE THREAD

**Issue by cwttdb70** [nuclearcodecat/shimmer#31]
The findbar is supposed to look like this

<img width="838" alt="Screenshot 2024-11-29 at 5 16 10 PM" src="https://github.com/user-attachments/assets/e5506adf-afe6-42b8-85a8-cc8b37cdb34b">

But on Mac, the background color / shape and the icons are missing, so that it actually looks like this:
<img width="1503" alt="Screenshot 2024-11-29 at 5 15 24 PM" src="https://github.com/user-attachments/assets/de3e8448-e00c-4d4f-8386-67f6eb402507">

**Comment by cwttdb70** [comment]
I am investigating

**Comment by cwttdb70** [comment]
Ok, the icons are not missing after all, they do show up on dark backgrounds, it's just that since the background mask is missing, they disappear on white backgrounds

<img width="935" alt="Screenshot 2024-11-29 at 5 22 06 PM" src="https://github.com/user-attachments/assets/b7493786-fdcf-4a60-9443-076ac50ca877">

**Comment by cwttdb70** [comment]
Problem solved by adding

`  background-color: var(--toolbar-bgcolor, var(--toolbar-non-lwt-bgcolor)) !important;
  -moz-appearance: none !important;`

to 

findbar:not([hidden]) {

Will submit PR

**Comment by cwttdb70** [comment]
@nuclearcodecat nevermind not sure how to properly submit a pull request but that's the fix, add:

`  background-color: var(--toolbar-bgcolor, var(--toolbar-non-lwt-bgcolor)) !important; -moz-appearance: none !important;`

to

`findbar:not([hidden]) {`

**Comment by nuclearcodecat** [comment]
thank you for the help angel!! i'll add this today and check out your mac winctr changes to see if they don't bite with anything else

**Comment by nuclearcodecat** [comment]
are sure you don't want to start a pull request? you'd be listed as a contributor @cwttdb70

**Comment by cwttdb70** [comment]
> are sure you don't want to start a pull request? you'd be listed as a contributor @cwttdb70 
> 
> 

Ok I'll do a pull request just need to clone the repo on my local machine...haven't done this in a while. Working on it now :)
