### ISSUE TITLE
native horizontal tabs stay visible when sidebery is activated -- how do i fix this?

### ISSUE THREAD

**Issue by d-aritos** [nuclearcodecat/shimmer#32]
not sure which setting i need to change to hide native horizontal tabs D:

**Comment by nuclearcodecat** [comment]
did you update the sidebery settings?

**Comment by d-aritos** [comment]
yes, it was just updated today, maybe it's a sidebery problem :(

**Comment by nuclearcodecat** [comment]
could you try following the installation instructions on a new firefox profile? this sounds like a sidebery preface problem to me but it's unlikely if you updated the settings. just so i can be sure we can rule that out, go to sidebery settings, search for "preface" (ctrl+f), and see if the "preface value" field has any sort of placeholder value. if it has "---", that's wrong. see images below

good
![image](https://github.com/user-attachments/assets/c2c66be0-cdc1-4e4a-88ab-b1a433f39ed1)
bad
![image](https://github.com/user-attachments/assets/57a434ab-2bd9-4f97-bf6b-9dd45fc745a7)

**Comment by d-aritos** [comment]
originally the preface value was written as "[Sidebery]" so I tried deleting it but there's no way of leaving the value empty for me :( If i try to empty the box the "---" is there by default.

**Comment by nuclearcodecat** [comment]
@d-aritos please read the installation instructions :3 you need to import sidebery settins, which set this preface value to an invisible character

**Comment by d-aritos** [comment]
i had imported the settings before, but i just re-imported the .json file and it worked again. thanks!
