### ISSUE TITLE
Dark theme options in select tag dropdown aren't properly adapted (?)

### ISSUE THREAD

**Issue by ParussMan** [nuclearcodecat/shimmer#35]
![image](https://github.com/user-attachments/assets/8736b8df-aca2-4902-94d5-95d52b77c7d5)

Black text over dark background is barely readable, also "disabled" attribute for an option has no dark theme styles and appears the same as for white theme

**Comment by nuclearcodecat** [comment]
what theme are you using

**Comment by nuclearcodecat** [comment]
ok could you check if you're on the newest version? i just fixed this yeserday. i'll see the unavailable options soon

**Comment by ParussMan** [comment]
yep I'm sorry I wasn't on the latest version and the only remaining issue is the disabled one now, thank you

**Comment by nuclearcodecat** [comment]
updated :3

**Comment by nuclearcodecat** [comment]
not sure if the colors are desirable, couldn't really pick a good one. hope it looks fine
