### ISSUE TITLE
newtab main container visible when everything inside hidden

### ISSUE THREAD

**Issue by vanloc0301** [nuclearcodecat/shimmer#36]
I want suggest remove this element when user turn off all suggest shortcut, default it look like:
![ảnh](https://github.com/user-attachments/assets/5c3409b7-6ec5-4bd5-a3f0-4756ed076af1)
CSS code:
```
.ds-outer-wrapper-breakpoint-override main { display: none; }
```
After add this CSS it will be look like this:
![ảnh](https://github.com/user-attachments/assets/ed04e804-108c-4714-b120-33e0fc690a10)
I just add this css to `chrome.css`:
I can manually edit but I think you can add this is addition feature in `about:config` to toggle true/false.
This very small suggest.

**Comment by nuclearcodecat** [comment]
how about moving the text to another place, like a corner of the screen? i don't want to hide the text, i think the photographer deserves to have their attribution

**Comment by vanloc0301** [comment]
> ....like a corner of the screen?
I think this good choice.

**Comment by nuclearcodecat** [comment]
done
