### ISSUE TITLE
Option to resize URL bar text

### ISSUE THREAD

**Issue by djenttleman** [nuclearcodecat/shimmer#4]
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/7308fc29-51ab-4337-a1b0-5ac9d7b1a54a">

As shown here, url text and site are big

How to change it?

Thanks

**Comment by djenttleman** [comment]
> in firefox, click on the top right hamburger menu > more tools > customize toolbar. see if you have any "flexible space" elements added

Where can I resize the text in the css? maybe is there inside.

**Comment by nuclearcodecat** [comment]
ah sorry i didn't catch that. ignore my previous comment. if you'd like to resize the text in the urlbar, find a reference to `#urlbar-input` in the code. then use `font-size: 1rem;` to decrease the size. you can play with the value. if you want to change how bold the text is - use `font-weight: 500 !important;`. you can also try 400, etc.
