### ISSUE TITLE
permenant bar on bottom

### ISSUE THREAD

**Issue by moonfight1** [nuclearcodecat/shimmer#6]
![image](https://github.com/user-attachments/assets/612bfd28-b833-4625-94e7-dd77a2bad015)

**Comment by nuclearcodecat** [comment]
it's on purpose, i will add a customization option tomorrow so you can remove it

**Comment by moonfight1** [comment]
what is the purpose of it tho

**Comment by nuclearcodecat** [comment]
looks better when you have sidebery enabled enabled, check the screenshots

**Comment by nuclearcodecat** [comment]
meh it looks better without the border when sidebar is hidden, i'll remove it. thanks for help. fixed in v2.2
