### ISSUE TITLE
Search bar not centered

### ISSUE THREAD

**Issue by BeeverFeever** [nuclearcodecat/shimmer#7]
I can't figure out how to get a screenshot of it as whenever I press the screenshot button the searchbar closes before the screenshot is taken. The search bar is slightly left of center most of the time. I'm using i3 so I typically have firefox taking up the whole screen but if I make it floating and resize it there is some widths that the search bar is centered. I'm also not using sidebery. 

This is probably very vague as I'm not entirely sure what other information I can give. I am looking to see if I can figure out the problem/solution myself but I don't know if I will be able to.

**Comment by nuclearcodecat** [comment]
honestly i never made it centered. i just made it float and increased its size to something ridiculous and it capped itself somehow. look at how it looks in the video (https://www.reddit.com/r/FirefoxCSS/s/vaglREyIsM). you can send me a screenshot if something's wrong, read my response on your other issue on how to do that.

**Comment by BeeverFeever** [comment]
![image](https://github.com/user-attachments/assets/3bebd50c-05ca-4cb8-8c00-28e253de14a6)

Ah ok I see.

**Comment by BeeverFeever** [comment]
I guess it's not a problem just thought that it should have been centered. I didn't look at the video close enough before now.
